language: ruby
script: bundle exec rake --trace
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - ruby-head
env: ARUBA_TIMEOUT=120 RAILS_ENV=development AHN_ENV=development
notifications:
  irc: "irc.freenode.org#adhearsion"
